var nodemailer = require('nodemailer');
const configs = require('./configs');


var transport = nodemailer.createTransport({
    host: configs.MAIL_HOST,
    port: configs.MAIL_PORT,
    auth: {
        user: configs.MAIL_USER, //example of generated by Mailtrap 
        pass: configs.MAIL_PASS //example of generated by Mailtrap 
    }
});


const imageLinkTest = `https://th.bing.com/th/id/R.d1fa037b255c3dab37cf6a89f8a1632c?rik=4pmJ8FdWyOIY8w&pid=ImgRaw&r=0`;
module.exports = {
    send: async function (email, message) {
        await transport.sendMail({
            from: 'iamasystemadmin@gmail.com',
            to: email,
            subject: 'RESET PASSWORD',
            html: `<a href='/authen/resetPassword/${message}'>bam vao day de doi mat khau</a>
                <img src="${imageLinkTest}" alt="Test Image"/>`,
        })
    },
}